In [46]:
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [47]:
#from sklearn.datasets import load_iris
#i=load_iris()

In [48]:
names= ["sepal length", "sepal width", "petal length", "petal width", "class"]
url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
i=pd.read_csv(url, names = names)
print(i.head())
print(i.shape)

   sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
(150, 5)


In [49]:
# y-Werte (class) sind kategorial. Aber NN arbeitet besser mit numerische Daten -> Umwandeln
y=i.select_dtypes(include=[object])
print(y)
from sklearn import preprocessing
le= preprocessing.LabelEncoder()

# passen den Etikettencodierer an und geben sie zurückt
y=y.apply(le.fit_transform) 
print(y)

              class
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
5       Iris-setosa
6       Iris-setosa
7       Iris-setosa
8       Iris-setosa
9       Iris-setosa
10      Iris-setosa
11      Iris-setosa
12      Iris-setosa
13      Iris-setosa
14      Iris-setosa
15      Iris-setosa
16      Iris-setosa
17      Iris-setosa
18      Iris-setosa
19      Iris-setosa
20      Iris-setosa
21      Iris-setosa
22      Iris-setosa
23      Iris-setosa
24      Iris-setosa
25      Iris-setosa
26      Iris-setosa
27      Iris-setosa
28      Iris-setosa
29      Iris-setosa
..              ...
120  Iris-virginica
121  Iris-virginica
122  Iris-virginica
123  Iris-virginica
124  Iris-virginica
125  Iris-virginica
126  Iris-virginica
127  Iris-virginica
128  Iris-virginica
129  Iris-virginica
130  Iris-virginica
131  Iris-virginica
132  Iris-virginica
133  Iris-virginica
134  Iris-virginica
135  Iris-virginica
136  Iris-virginica
137  Iris-virginica


In [50]:
X=i.iloc[:, 0:4]


In [51]:
# Aufteilen Daten in Trainingsdaten und Testdaten
from sklearn.model_selection import  train_test_split
X_train, X_test, y_train, y_test = train_test_split (X,y, test_size=0.20) # teilt 20% des Datensatzes in Testdaten auf. 80% für TRaining

In [52]:
# Daten Vorverarbeitung
# Merkmalskalierung: erfolgt nur für TRainingsdaten

from sklearn.preprocessing import StandardScaler
s = StandardScaler()

# nur für Trainingdaten
s.fit(X_train) # Berechnen den Mittelwert und die Standardabweichung für die später Skalierung

# Anwendung der Transformationen auf die Daten  x = (x-mean(x))/std(x)
X_train_std = s.transform(X_train)
X_test_std = s.transform(X_test)

print(X_train_std)
print((X_train_std).mean(axis=0)) # Der arithmetische Mittelwert des Spalte ~ 0
print((X_train_std).std(axis=0))  # Standardabweichung =1 



[[ 1.09203865  0.63395731  1.13296244  1.22099444]
 [-1.52387142  0.40481611 -1.37608743 -1.33301228]
 [ 0.09550148  0.40481611  0.60781247  0.81773022]
 [-1.15016998 -1.19917226  0.43276248  0.68330881]
 [-1.77300571  0.40481611 -1.43443743 -1.33301228]
 [ 0.22006862 -0.28260748  0.43276248  0.414466  ]
 [-0.15363281 -0.51174867  0.19936249  0.14562319]
 [-0.27819996 -0.74088987  0.25771249  0.14562319]
 [-0.02906567 -0.74088987  0.78286246  0.95215163]
 [ 2.33771011  1.7796633   1.71646241  1.35541584]
 [-1.77300571 -0.28260748 -1.37608743 -1.33301228]
 [-0.90103569  1.09223971 -1.37608743 -1.19859087]
 [-0.15363281  3.15451048 -1.31773743 -1.06416946]
 [ 1.71487438  1.3213809   1.36636243  1.75868006]
 [-0.52733425  2.00880449 -1.20103744 -1.06416946]
 [-0.02906567 -0.74088987  0.0826625   0.01120178]
 [-0.52733425 -0.05346628  0.43276248  0.414466  ]
 [ 1.34117294  0.17567492  0.95791245  1.22099444]
 [ 0.34463577 -0.05346628  0.49111248  0.2800446 ]
 [-0.02906567 -0.74088987  0.78

In [53]:
#Training und Vorhersagen

from sklearn.neural_network import MLPClassifier
mlp= MLPClassifier (hidden_layer_sizes =(10,10), activation="tanh", alpha=0.1, solver="sgd", max_iter= 2000)
mlp.fit(X_train, y_train.values.ravel())# trainiert auf TRainingdaten. (ravel: gibt uns 1-D Array zurückt)

MLPClassifier(activation='tanh', alpha=0.1, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10, 10), learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='sgd', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [54]:
# Vorhersagen, p= predictions
y_pred = mlp.predict(X_test)

In [55]:
# Berwertung des Algorithmus
from sklearn.metrics import classification_report, confusion_matrix

# Konfusionsmatrix: zur bewertung der Genauigkeit einer Klassifizierung
print(confusion_matrix(y_test, y_pred, labels=[0,1,2]))
print(classification_report(y_test, y_pred))

[[11  0  0]
 [ 0  6  1]
 [ 0  0 12]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        11
          1       1.00      0.86      0.92         7
          2       0.92      1.00      0.96        12

avg / total       0.97      0.97      0.97        30



In [56]:
print(mlp.coefs_[0])

[[ 0.45648203 -0.10488973  0.09683492 -0.12188549 -0.62184474  0.30819875
  -0.22366331  0.29264098 -0.6017627   0.38705529]
 [-0.08263832  0.54967211  0.28244718  0.80612716 -0.58160719  0.29932763
   0.29535273 -0.0474325  -0.42208713 -0.35711581]
 [-0.24351292 -0.44152888  0.0470942  -0.50391657  0.54236834 -0.49115306
  -0.080909   -0.12001769  0.81974489  0.23587034]
 [ 0.36284092 -0.59198295  0.03784777 -0.15930053 -0.24499229 -0.50695321
  -0.63589837 -0.03173565  0.66526305 -0.50650635]]


In [57]:
print(mlp.intercepts_[0])


[-0.2838072   0.25998003  0.60420523  0.34573497 -0.08487395  0.34413407
 -0.59691412  0.25375713 -0.10320722 -0.56676979]


In [70]:
from sklearn.model_selection import GridSearchCV

parameters ={"activation":["identity", "logistic", "tanh", "relu"],
             "solver":["lbfgs", "sgd", "adam"],
             "alpha":[0.001, 0.01, 0.1, 1, 10, 100],
             "learning_rate":["constant", "invscaling", "adaptive"]}

GS=GridSearchCV(estimator= MLPClassifier( hidden_layer_sizes= (10,10), max_iter=2000, random_state=1, early_stopping= True),
                 param_grid=parameters)

GS.fit(X_train, y_train.values.ravel())
# > 1 Minute

GridSearchCV(cv=None, error_score='raise',
       estimator=MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=True, epsilon=1e-08,
       hidden_layer_sizes=(10, 10), learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'activation': ['identity', 'logistic', 'tanh', 'relu'], 'solver': ['lbfgs', 'sgd', 'adam'], 'alpha': [0.001, 0.01, 0.1, 1, 10, 100], 'learning_rate': ['constant', 'invscaling', 'adaptive']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [80]:
p= GS.predict(X_test)
print(classification_report(y_test, p))



             precision    recall  f1-score   support

          0       1.00      1.00      1.00        11
          1       1.00      0.86      0.92         7
          2       0.92      1.00      0.96        12

avg / total       0.97      0.97      0.97        30



In [72]:

print(GS.best_estimator_.score(X_test, y_test))

0.9666666666666667


In [73]:
print(GS.best_estimator_)

MLPClassifier(activation='identity', alpha=1, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=True, epsilon=1e-08,
       hidden_layer_sizes=(10, 10), learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)


In [74]:
print(GS.best_score_)

0.9833333333333333


In [75]:
print(GS.best_params_)

{'activation': 'identity', 'alpha': 1, 'learning_rate': 'constant', 'solver': 'lbfgs'}


In [76]:
from sklearn.model_selection import RandomizedSearchCV
params= {"activation":["identity", "logistic", "tanh", "relu"],
             "solver":["lbfgs", "sgd", "adam"],
             "alpha":[0.001, 0.01, 0.1, 1, 10, 100],
             "learning_rate":["constant", "invscaling", "adaptive"]}
RS= RandomizedSearchCV (estimator=MLPClassifier( hidden_layer_sizes= (20,), max_iter=1000, random_state=1, early_stopping= True),
                 param_distributions=params, n_iter=20)
RS.fit(X_train, y_train.values.ravel())


RandomizedSearchCV(cv=None, error_score='raise',
          estimator=MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=True, epsilon=1e-08,
       hidden_layer_sizes=(20,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False),
          fit_params=None, iid=True, n_iter=20, n_jobs=1,
          param_distributions={'activation': ['identity', 'logistic', 'tanh', 'relu'], 'solver': ['lbfgs', 'sgd', 'adam'], 'alpha': [0.001, 0.01, 0.1, 1, 10, 100], 'learning_rate': ['constant', 'invscaling', 'adaptive']},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score='warn', scoring=None, verbose=0)

In [77]:
print (RS.best_estimator_)

MLPClassifier(activation='identity', alpha=0.001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=True, epsilon=1e-08,
       hidden_layer_sizes=(20,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)


In [78]:
print(RS.best_score_)

0.975


In [79]:
print(RS.best_params_)

{'solver': 'lbfgs', 'learning_rate': 'constant', 'alpha': 0.001, 'activation': 'identity'}
